export const projects = {
    title: "Featured Work",
    personalProjects: [
      {
        title: "Popcorn Movie DB",
        short:
          "Popcorn Movies is a fully responsive movie database web application created using React JS and SASS for CSS pre-processing. The content is dynamically generated by pulling individual movie data via the TMDB (The Movie Database) REST API.",
        description1:
          "The primary goal was to create an intuitive and easy to use platform (in case you don't like using or have a grudge against IMDB) that provides users with details on their favourite movies or those they're excited about that have yet to be released.",
        description2:
            "Movie data is pulled in via the TMDB API as JSON data using asynchronous fetch requests which is then parsed and displayed using several of React's Hooks and functions.",
        description_list: ["useState", "useEffect", "useContext", "useReducer", "Global State"],
        technologies: ["React.js", "SASS", "Adobe XD, Adobe Photoshop"],
        github: "https://github.com/MGravitee/popcorn-movie-react-app",
        demo: "https://mattgravitee.com/popcorn-movie/",
      },
      {
        title: "Saje Useability Report",
        short:
          "A comprehensive audit of Saje's website to evaluate and improve the user's experience and boost conversion rates.",
        description:
          "As a team we conducted qualitative and quantitative research along with useability tests and think-aloud data on a group of based on members of our target audience.These tests were used to identify pain-points as well as user positives.",
        description2:
          "We then then analyzed the results using a combination of System Useability Scale (SUS) questions, and think-aloud observations to provide prioritized, data-driven recommendations and accompanying design suggestions.",
        description_list: ["First Click Test", "Preference Test", "Five Second Test", "Useability Tasks", "Think-Aloud Responses"],
        technologies: ["Figma", "Lyssna", "UXPressia", "MSOffice"],
        github: "https://www.saje.ca/",
        demo: "#",
      },
      {
        title: "Who's That Pokémon?!?",
        short:
          "Who's That Pokémon?!? is a browser-based, vanilla JavaScript word guessing game similar to wheel of fortune (but without Pat Sajak or prizes) based on the popular Pokémon franchise (please don't sue me Nintendo).",
        description:
          "Every word you need to guess is the name of one of the 150 (151 if we count Mew) first generation Pokémon. The object of the game is to guess as many as you can correctly within the time limit.",
          description2:
          "At the beginning of the development process, I was using basic Alerts for in-game messages/direction but as it progressed, I felt more confident in my abilities and decided to create and animate my own modals.",
        description_list: ["Objects", "Classes", "Array Destructuring"],
        technologies: [
          "HTML5",
          "CSS3",
          "JavaScript",
          "Adobe Photoshop",
          "Adobe Illustrator",
        ],
        github: "https://github.com/MGravitee/game-js",
        demo: "#",
      },
    ],
  };